"""LockFeature: the capability bits a lock advertises in its feature value."""

from __future__ import annotations

from enum import IntEnum


class LockFeature(IntEnum):
    """Bit positions of the lock's feature value - mirror of `FeatureValue.java` in the SDK.

    The value of each member is the bit index the official SDK tests with
    `FeatureValueUtil.isSupportFeature`, not a mask. `VirtualKey.has_feature`
    performs the same test on the cloud-provided feature value. The one
    spelling fix is `FIRMWARE_SETTING`, which the SDK misspells.
    """

    PASSCODE = 0
    IC = 1
    FINGER_PRINT = 2
    WRIST_BAND = 3
    AUTO_LOCK = 4
    PASSCODE_WITH_DELETE_FUNCTION = 5
    FIRMWARE_SETTING = 6
    MODIFY_PASSCODE_FUNCTION = 7
    MANUAL_LOCK = 8
    PASSWORD_DISPLAY_OR_HIDE = 9
    GATEWAY_UNLOCK = 10
    FREEZE_LOCK = 11
    CYCLIC_PASSWORD = 12
    MAGNETOMETER = 13
    CONFIG_GATEWAY_UNLOCK = 14
    AUDIO_MANAGEMENT = 15
    NB_LOCK = 16
    GET_ADMIN_CODE = 18
    HOTEL_LOCK = 19
    LOCK_NO_CLOCK_CHIP = 20
    SUPPORT_CLOSE_BLUETOOTH_ADVERTISING = 21
    PASSAGE_MODE = 22
    PASSAGE_MODE_AND_AUTO_LOCK_AND_CAN_CLOSE = 23
    WIRELESS_KEYBOARD = 24
    LAMP = 25
    TAMPER_ALERT = 28
    RESET_BUTTON = 29
    PRIVACY_LOCK = 30
    DEAD_LOCK = 32
    CYCLIC_IC_OR_FINGER_PRINT = 34
    UNLOCK_DIRECTION = 36
    FINGER_VEIN = 37
    TELINK_CHIP = 38
    NB_ACTIVITE_CONFIGURATION = 39
    CYCLIC_PASSCODE_CAN_RECOVERY = 40
    REMOTE = 41
    ACCESSORY_BATTERY = 42
    SOUND_VOLUME_AND_LANGUAGE_SETTING = 43
    QR_CODE = 44
    DOOR_SENSOR = 45
    PASSAGE_MODE_AUTO_UNLOCK_SETTING = 46
    FINGERPRINT_DISTRIBUTION = 47
    ZHONG_ZHENG = 48
    SYNO = 49
    WIRELESS_DOOR_SENSOR = 50
    DOOR_OPEN_ALARM = 51
    SENSITIVITY = 52
    FACE_3D = 53
    SUPPORT_MOTOR_TORQUE_SETTING = 54
    CPU_CARD = 55
    WIFI_LOCK = 56
    WIFI_LOCK_SUPPORT_STATIC_IP = 58
    INCOMPLETE_PASSCODE = 60
    SUPPORT_DOUBLE_CHECK = 63
    APP_AUTH_UNLOCK = 64
    GATEWAY_AUTH_UNLOCK = 65
    DO_NOT_SUPPORT_APP_AND_GATEWAY_UNLOCK = 66
    SUPPORT_XM = 67
    ON_MICRO_CHIP = 68
    ZHI_AN_FACE_DELIVERY = 69
    PALM_VEIN = 70
    SUPPORT_GRASS = 75
    RESET_LOCK_BY_CODE = 76
    SUPPORT_THIRD_PARTY_BLUETOOTH_DEVICE = 77
    AUTO_SET_ANGLE = 78
    MANUAL_SET_ANGLE = 79
    CONTROL_LATCH_BOLT = 80
    AUTO_SET_UNLOCK_DIRECTION = 81
    SUPPORT_IC_CARD_SECURITY_SETTING = 82
    SUPPORT_WIFI_SLEEP_MODE_TIMES_SETTING = 83
    SUPPORT_MULTI_FUNCTION_KEYPAD = 84
    DO_NOT_SUPPORT_TURN_OFF_LATCH_BOLT = 85
    SUPPORT_PUBLIC_MODE_SETTING = 86
    SUPPORT_LOW_BATTERY_UNLOCK_SETTING = 87
    SUPPORT_MOTOR_DRIVE_TIME_SETTING = 88
    SUPPORT_MODIFY_FEATURE_VALUE = 89
    SUPPORT_MODIFY_LOCK_NAME_PREFIX = 90
    SUPPORT_AUTH_CODE = 92
    UNAUTHORIZED_ATTEMPT_ALARM = 93
    SUPPORT_CLEAR_PASSCODE_AND_DYNAMIC_PASSCODE_SETTING = 95
    POWER_SAVER_SUPPORT_WIFI = 96
    SUPPORT_BLUETOOTH_ADVERTISING_SETTING = 97
    SUPPORT_WORKING_TIMES = 98
    SUPPORT_SUPPLIER_CODE = 99
    SUPPORT_CAT_ONE = 100
    SUPPORT_FORCED_OPENING_DOOR_ALARM = 102
    ZHI_AN_FACE_FEATURE_SECOND_GENERATION = 103
    SUPPORT_DEAD_LOCKING = 106
    SUPPORT_CUSTOM_QR_CODE = 108
    SUPPORT_SAFE_M1_CARD = 109
    YI_SHENG_FACE_DELIVERY = 110
    SUPPORT_PICTURE_FACE_DELIVERY = 112
    SUPPORT_SET_ALIAS = 114
    HIDE_WIFI_CAT_ONE_SLEEP_MODE_SETTING = 117
    SUPPORT_SEMI_AUTOMATIC_MODE_CONTROL = 119
    SUPPORT_LOCK_SUPERVISION = 126
