"""Command opcodes carried in the V3 frame header.

Values mirror `com.ttlock.bl.sdk.command.Command` in the official Android
SDK for `lockType=5` (V3), listed in ascending opcode order.
"""

from __future__ import annotations

CMD_SEARCH_DEVICE_FEATURE = 0x01
CMD_MANAGE_KEYBOARD_PASSWORD = 0x03
CMD_MANAGE_FINGERPRINT = 0x06  # COMM_FR_MANAGE; only the list sub-op (0x06) is implemented
CMD_GET_PASSCODES = 0x07  # COMM_PWD_LIST
CMD_QUERY_STATE = 0x14
CMD_GET_AES_KEY = 0x19
CMD_GET_OPERATE_LOG = 0x25
CMD_CHECK_RANDOM = 0x30
CMD_INIT_PASSWORDS = 0x31
CMD_GET_LOCK_TIME = 0x34
CMD_AUTO_LOCK_MANAGE = 0x36
CMD_CHECK_ADMIN = 0x41
CMD_TIME_CALIBRATE = 0x43
CMD_UNLOCK = 0x47
CMD_RESPONSE = 0x54
CMD_CHECK_USER_TIME = 0x55
CMD_LOCK = 0x58  # COMM_FUNCTION_LOCK
CMD_SET_LOCK_SOUND = 0x62  # COMM_AUDIO_MANAGE
CMD_SWITCH = 0x68
CMD_GET_DEVICE_PROPERTIES = 0x90  # COMM_READ_DEVICE_INFO

APICMD_UNLOCK_BY_ADMIN = 3
APICMD_UNLOCK_BY_USER = 4
APICMD_LOCK_BY_ADMIN = 13
APICMD_LOCK_BY_USER = 14
