name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    uses: roquerodrigo/.github/.github/workflows/sdk-lint.yml@v2

  tests:
    needs: lint
    uses: roquerodrigo/.github/.github/workflows/sdk-tests.yml@v2
